using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BookPromoterAI.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddWeeklyVideoFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerated",
                table: "TikTokVideos",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "NarrationText",
                table: "TikTokVideos",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "WeekLabel",
                table: "TikTokVideos",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "WeekNumber",
                table: "TikTokVideos",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "WeekYear",
                table: "TikTokVideos",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AutoGenerated",
                table: "TikTokVideos");

            migrationBuilder.DropColumn(
                name: "NarrationText",
                table: "TikTokVideos");

            migrationBuilder.DropColumn(
                name: "WeekLabel",
                table: "TikTokVideos");

            migrationBuilder.DropColumn(
                name: "WeekNumber",
                table: "TikTokVideos");

            migrationBuilder.DropColumn(
                name: "WeekYear",
                table: "TikTokVideos");
        }
    }
}
